### ISSUE TITLE
Uncaught TypeError: Cannot read property 'prototype' of undefined

### ISSUE THREAD

**Issue by cyanpunk** [AnthonyCalandra/todo-list#14]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.209.0
**System**: Mac OS X 10.10.3
**Thrown From**: [todo-list](https://github.com/AnthonyCalandra/todo-list) package, v1.0.0

### Stack Trace

Uncaught TypeError: Cannot read property 'prototype' of undefined

```
At /Users/Austris/.atom/packages/todo-list/lib/todo-list-view.coffee:5

TypeError: Cannot read property 'prototype' of undefined
  at __extends (/Users/Austris/.atom/packages/todo-list/lib/todo-list-view.coffee:5:199)
  at /Users/Austris/.atom/packages/todo-list/lib/todo-list-view.coffee:5:3
  at Object.<anonymous> (/Users/Austris/.atom/packages/todo-list/lib/todo-list-view.coffee:267:5)
  at Object.<anonymous> (/Users/Austris/.atom/packages/todo-list/lib/todo-list-view.coffee:1:1)
  at Module._compile (module.js:452:26)
  at Object.requireCoffeeScript (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (/Users/Austris/.atom/packages/todo-list/lib/todo-list.coffee:1:16)
  at Object.<anonymous> (/Users/Austris/.atom/packages/todo-list/lib/todo-list.coffee:1:1)
  at Module._compile (module.js:452:26)
  at Object.requireCoffeeScript (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Package.module.exports.Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:709:34)
  at Package.module.exports.Package.activateConfig (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:257:12)
  at PackageDetailView.module.exports.PackageDetailView.activate (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-detail-view.js:163:26)
  at PackageDetailView.module.exports.PackageDetailView.updateInstalledState (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-detail-view.js:201:12)
  at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-detail-view.js:235:24
  at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/emissary/lib/emitter.js:155:30
  at Array.forEach (native)
  at PackageManager.module.exports.Emitter.emitSlow (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/emissary/lib/emitter.js:154:47)
  at PackageManager.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/emissary/lib/emitter.js:107:30)
  at PackageManager.module.exports.PackageManager.emitPackageEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:546:19)
  at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:369:26
  at exit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:53:16)
  at triggerExitCallback (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:213:47)
  at ChildProcess.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:235:18)
  at emitTwo (events.js:87:13)
  at ChildProcess.emit (events.js:169:7)
  at Process.ChildProcess._handle.onexit (child_process.js:1057:12)

```

### Commands

```
     -0:45.6.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {
    "destroyEmptyPanes": false
  }
}
```

### Installed Packages

```coffee
# User
autocomplete-paths, v1.0.2
autocomplete-ruby, v0.1.0
autocomplete-sass, v0.1.0
autohide-tree-view, v0.20.1
chary-tree-view, v0.2.3
color-picker, v2.0.4
editor-stats, v0.17.0
file-icons, v1.5.7
filesize, v0.2.0
flex-tool-bar, v0.4.2
git-projects, v1.14.1
git-tab-status, v1.9.2
gutter-shadow, v0.5.0
highlight-selected, v0.9.3
keyboard-scroll, v0.4.0
keyboard-sounds, v0.2.0
language-dotenv, v1.0.0
language-fish-shell, v1.0.2
language-generic-config, v0.2.0
language-gitignore, v0.2.0
language-hosts, v0.1.2
language-slim, v0.4.0
linter, v0.12.7
minimap, v4.10.0
minimap-bookmarks, v0.1.0
minimap-find-and-replace, v4.2.0
minimap-git-diff, v4.1.3
minimap-highlight-selected, v4.3.0
minimap-pigments, v0.1.1
minimap-selection, v4.2.0
open-recent, v2.2.4
pigments, v0.5.0
save-session, v0.15.5
symbols-tree-view, v0.9.3
tool-bar, v0.1.7
tool-bar-main, v0.0.8
tree-view-git-status, v0.1.1
web-browser, v1.5.0

# Dev
No dev packages
```

**Comment by nrozic** [comment]
Same here, after installing package I got error "Uncaught TypeError: Cannot read property 'prototype' of undefined"

1. Install todo-list package

**Atom Version**: 1.0.0
**System**: Mac OS X 10.10.3
**Thrown From**: [todo-list](https://github.com/AnthonyCalandra/todo-list) package, v1.0.0


### Stack Trace

Uncaught TypeError: Cannot read property 'prototype' of undefined

```
At /Users/trilium-mac/.atom/packages/todo-list/lib/todo-list-view.coffee:5

TypeError: Cannot read property 'prototype' of undefined
  at __extends (/Users/trilium-mac/.atom/packages/todo-list/lib/todo-list-view.coffee:5:199)
  at /Users/trilium-mac/.atom/packages/todo-list/lib/todo-list-view.coffee:5:3
  at Object.<anonymous> (/Users/trilium-mac/.atom/packages/todo-list/lib/todo-list-view.coffee:267:5)
  at Object.<anonymous> (/Users/trilium-mac/.atom/packages/todo-list/lib/todo-list-view.coffee:1:1)
  at Module._compile (module.js:452:26)
  at Object.requireCoffeeScript (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (/Users/trilium-mac/.atom/packages/todo-list/lib/todo-list.coffee:1:16)
  at Object.<anonymous> (/Users/trilium-mac/.atom/packages/todo-list/lib/todo-list.coffee:1:1)
  at Module._compile (module.js:452:26)
  at Object.requireCoffeeScript (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Package.module.exports.Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:709:34)
  at Package.module.exports.Package.activateConfig (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:257:12)
  at PackageDetailView.module.exports.PackageDetailView.activate (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-detail-view.js:163:26)
  at PackageDetailView.module.exports.PackageDetailView.updateInstalledState (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-detail-view.js:201:12)
  at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-detail-view.js:235:24
  at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/emissary/lib/emitter.js:155:30
  at Array.forEach (native)
  at PackageManager.module.exports.Emitter.emitSlow (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/emissary/lib/emitter.js:154:47)
  at PackageManager.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/emissary/lib/emitter.js:107:30)
  at PackageManager.module.exports.PackageManager.emitPackageEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:546:19)
  at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:369:26
  at exit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:53:16)
  at triggerExitCallback (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:213:47)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:227:18
  at Socket.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:98:18)
  at emitOne (events.js:82:20)
  at Socket.emit (events.js:166:7)
  at Pipe.close (net.js:464:12)

```

### Commands

```
     -9:55.6.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  6x -6:21.9.0 core:backspace (atom-text-editor.editor.mini.is-focused)
  3x -6:19.7.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -3:37.5.0 command-palette:toggle (atom-text-editor.editor.mini.is-focused)
 25x -3:30 core:move-down (atom-text-editor.editor.mini.is-focused)
  2x -3:19.1.0 core:move-up (atom-text-editor.editor.mini.is-focused)
 45x -3:17.1.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -2:57.4.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -2:57.4.0 git-diff-details:close-git-diff-details (atom-text-editor.editor.mini.is-focused)
     -2:57.4.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -0:42.1.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-material-ui",
      "atom-material-syntax"
    ],
    "disabledPackages": [
      "remote-edit"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-lorempixel, v0.1.0
atom-material-syntax, v0.1.1
atom-material-ui, v0.4.9
colorful-json, v1.0.0
css-color-underline, v1.0.1
docblockr, v0.7.2
emmet, v2.3.10
flex-tool-bar, v0.4.2
git-diff-details, v0.18.0
git-log, v0.4.1
language-blade, v0.14.0
laravel, v0.7.0
markdown-pdf, v1.3.7
method-separator, v0.1.3
minimap, v4.10.0
minimap-bookmarks, v0.1.0
minimap-color-highlight, v4.1.4
minimap-git-diff, v4.1.3
sass-watch, v0.3.1
tool-bar, v0.1.8
tool-bar-main, v0.0.8
tree-view-git-modified, v0.5.10
tree-view-git-status, v0.1.1
untitled-no-more, v0.1.0
useful-context-menu, v0.2.1
wakatime, v4.0.10
wordcount, v2.2.2

# Dev
No dev packages
```

**Comment by lorencs** [comment]
+1

**Comment by charleswson** [comment]
+1

**Comment by roquefsd** [comment]
+1

**Comment by joshschumacher** [comment]
This package is quite broken in recent versions of Atom. I started a fix but abandoned after continuing to hit roadblocks. I encourage someone else to take a look and finish up the PR - https://github.com/AnthonyCalandra/todo-list/pull/17
