### ISSUE TITLE
Failed to activate the todo-list package

### ISSUE THREAD

**Issue by adotrocks** [AnthonyCalandra/todo-list#15]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.211.0
**System**: Mac OS X 10.10.3
**Thrown From**: [todo-list](https://github.com/AnthonyCalandra/todo-list) package, v1.0.0

### Stack Trace

Failed to activate the todo-list package

```
At Cannot read property 'prototype' of undefined

TypeError: Cannot read property 'prototype' of undefined
  at __extends (/Users/alechp/.atom/packages/todo-list/lib/todo-list-view.coffee:1:1)
  at /Users/alechp/.atom/packages/todo-list/lib/todo-list-view.coffee:5:3
  at Object.<anonymous> (/Users/alechp/.atom/packages/todo-list/lib/todo-list-view.coffee:267:5)
  at Object.<anonymous> (/Users/alechp/.atom/packages/todo-list/lib/todo-list-view.coffee:1:1)
  at Module._compile (module.js:452:26)
  at Object.requireCoffeeScript (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (/Users/alechp/.atom/packages/todo-list/lib/todo-list.coffee:1:16)
  at Object.<anonymous> (/Users/alechp/.atom/packages/todo-list/lib/todo-list.coffee:1:1)
  at Module._compile (module.js:452:26)
  at Object.requireCoffeeScript (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Package.module.exports.Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:709:34)
  at Package.module.exports.Package.activateConfig (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:257:12)
  at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:236:14)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:772:25
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:222:20)
  at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61)
  at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:156:19)
  at EventEmitter.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:70:30)
  at emitOne (events.js:77:13)
  at EventEmitter.emit (events.js:166:7)

```

### Commands

```
     -0:05.1.0 todo-list:toggle-side (atom-text-editor.editor.is-focused)
     -0:00.4.0 todo-list:toggle (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
jshint, v1.3.7
linter-jsxhint, v0.1.2
linter-plus, v0.5.0
project-manager, v1.15.10
react, v0.12.0
todo-list, v1.0.0

# Dev
No dev packages
```

**Comment by jalama** [comment]
+1 seeing this also

Stack Trace https://gist.github.com/jalama/1543b6ec0ed41128d55f

User packages:
├── linter@1.5.0
├── linter-pylint@1.0.0
└── todo-list@1.0.0

**Comment by roquefsd** [comment]
+1

**Comment by harrislapiroff** [comment]
+1

**Comment by B1T0** [comment]
+1

**Comment by isaacbacon1** [comment]
+1

**Comment by kerberosdelhades** [comment]
+1

**Comment by jlgerber** [comment]
+1

**Comment by joshschumacher** [comment]
This package is quite broken in recent versions of Atom. I started a fix but abandoned after continuing to hit roadblocks. I encourage someone else to take a look and finish up the PR - https://github.com/AnthonyCalandra/todo-list/pull/17
