### ISSUE TITLE
Install failed: Cannot read property 'prototype' of undefined

### ISSUE THREAD

**Issue by GitWessel** [AnthonyCalandra/todo-list#18]
Cannot read property 'prototype' of undefined
Hide Stack Trace
TypeError: Cannot read property 'prototype' of undefined
    at __extends (file:///C:/Users/Wessel Beulink/.atom/packages/todo-list/lib/todo-list-view.coffee:1:1)
    at file:///C:/Users/Wessel Beulink/.atom/packages/todo-list/lib/todo-list-view.coffee:5:3
    at Object.<anonymous> (file:///C:/Users/Wessel Beulink/.atom/packages/todo-list/lib/todo-list-view.coffee:5:3)
    at Object.<anonymous> (file:///C:/Users/Wessel Beulink/.atom/packages/todo-list/lib/todo-list-view.coffee:1:1)
    at Module._compile (C:\Users\Wessel Beulink\AppData\Local\atom\app-1.3.3\resources\app.asar\src\native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (C:\Users\Wessel Beulink\AppData\Local\atom\app-1.3.3\resources\app.asar\src\compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (C:\Users\Wessel Beulink\AppData\Local\atom\app-1.3.3\resources\app.asar\src\native-compile-cache.js:50:27)
    at Object.<anonymous> (file:///C:/Users/Wessel Beulink/.atom/packages/todo-list/lib/todo-list.coffee:1:16)
    at Object.<anonymous> (file:///C:/Users/Wessel Beulink/.atom/packages/todo-list/lib/todo-list.coffee:1:1)
    at Module._compile (C:\Users\Wessel Beulink\AppData\Local\atom\app-1.3.3\resources\app.asar\src\native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (C:\Users\Wessel Beulink\AppData\Local\atom\app-1.3.3\resources\app.asar\src\compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (C:\Users\Wessel Beulink\AppData\Local\atom\app-1.3.3\resources\app.asar\src\native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (C:\Users\Wessel Beulink\AppData\Local\atom\app-1.3.3\resources\app.asar\src\package.js:663:34)
    at C:\Users\Wessel Beulink\AppData\Local\atom\app-1.3.3\resources\app.asar\src\package.js:115:28
    at Package.module.exports.Package.measure (C:\Users\Wessel Beulink\AppData\Local\atom\app-1.3.3\resources\app.asar\src\package.js:92:15)
    at Package.module.exports.Package.load (C:\Users\Wessel Beulink\AppData\Local\atom\app-1.3.3\resources\app.asar\src\package.js:106:12)
    at PackageManager.module.exports.PackageManager.loadPackage (C:\Users\Wessel Beulink\AppData\Local\atom\app-1.3.3\resources\app.asar\src\package-manager.js:438:14)
    at PackageManager.module.exports.PackageManager.activatePackage (C:\Users\Wessel Beulink\AppData\Local\atom\app-1.3.3\resources\app.asar\src\package-manager.js:516:30)
    at C:\Users\Wessel Beulink\AppData\Local\atom\app-1.3.3\resources\app.asar\node_modules\settings-view\lib\package-manager.js:444:29
    at exit (C:\Users\Wessel Beulink\AppData\Local\atom\app-1.3.3\resources\app.asar\node_modules\settings-view\lib\package-manager.js:73:16)
    at triggerExitCallback (C:\Users\Wessel Beulink\AppData\Local\atom\app-1.3.3\resources\app.asar\src\buffered-process.js:213:47)
    at ChildProcess.<anonymous> (C:\Users\Wessel Beulink\AppData\Local\atom\app-1.3.3\resources\app.asar\src\buffered-process.js:235:18)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)

**Comment by itsjustcon** [comment]
+1
