### ISSUE TITLE
Failed to load the todo-list package

### ISSUE THREAD

**Issue by petey** [AnthonyCalandra/todo-list#9]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.190.0
**System**: Mac OS X 10.10.3
**Thrown From**: [todo-list](https://github.com/AnthonyCalandra/todo-list) package, v1.0.0

### Stack Trace

Failed to load the todo-list package

```
At Cannot read property 'prototype' of undefined

TypeError: Cannot read property 'prototype' of undefined
    at __extends (/Users/petey/.atom/packages/todo-list/lib/todo-list-view.coffee:5:199)
    at /Users/petey/.atom/packages/todo-list/lib/todo-list-view.coffee:10:5
    at Object.<anonymous> (/Users/petey/.atom/packages/todo-list/lib/todo-list-view.coffee:267:5)
    at Object.<anonymous> (/Users/petey/.atom/packages/todo-list/lib/todo-list-view.coffee:269:4)
    at Module._compile (module.js:452:26)
    at Object.requireCoffeeScript (/Applications/Atom.app/Contents/Resources/app/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
    at Module.load (module.js:347:32)
    at Function.Module._load (module.js:302:12)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "metrics",
      "package-js-generator",
      "cucumber-step",
      "coffee-compile",
      "git-grep"
    ]
  },
  "todo-list": {
    "showOnRightSide": true
  }
}
```

### Installed Packages

```coffee
# User
atom-yamljson, v0.2.3
autocomplete-plus, v2.9.0
autocomplete-snippets, v1.2.0
cucumber, v0.5.0
docblockr, v0.6.3
file-icons, v1.5.3
git-history, v2.3.0
git-plus, v4.4.12
git-tab-status, v1.6.0
javascript-snippets, v1.0.0
language-chef, v0.4.0
linter, v0.12.0
linter-csslint, v0.0.11
linter-js-yaml, v1.0.0
linter-jshint, v0.1.1
linter-jsonlint, v0.1.2
markdown-scroll-sync, v0.3.2
nuclear-force, v1.0.0
pretty-json, v0.3.2
project-ring, v0.19.6
react, v0.11.2
regex-railroad-diagram, v0.7.4
symbols-tree-view, v0.9.2
todo-list, v1.0.0

# Dev
No dev packages
```

**Comment by AnthonyCalandra** [comment]
Thanks for the report. I'm assuming you weren't able to reproduce this error?

**Comment by petey** [comment]
This occurred immediately after starting atom when it was upgraded. I haven't seen it since.

**Comment by pharmaline** [comment]
After Upgrade Atom Version 1.1.0 i got the same Error. Is there a solution??

**Comment by AnthonyCalandra** [comment]
Not yet. The next version will have a fix for this, but there are a lot of API changes I need to make since this came out during pre-1.0 Atom. No ETA yet.

**Comment by stojanovicigi** [comment]
I have the same error as well.

**Comment by sammychiang** [comment]
same problem

**Comment by drodrigo** [comment]
I'm also having this problem...

---- ---- -----
**Atom Version**: 1.1.0
**System**: Mac OS X 10.10.3
**Thrown From**: [todo-list](https://github.com/AnthonyCalandra/todo-list) package, v1.0.0


### Stack Trace

Failed to load the todo-list package

```
At Cannot read property 'prototype' of undefined

TypeError: Cannot read property 'prototype' of undefined
    at __extends (/Users/Arthur/.atom/packages/todo-list/lib/todo-list-view.coffee:1:1)
    at /Users/Arthur/.atom/packages/todo-list/lib/todo-list-view.coffee:5:3
    at Object.<anonymous> (/Users/Arthur/.atom/packages/todo-list/lib/todo-list-view.coffee:5:3)
    at Object.<anonymous> (/Users/Arthur/.atom/packages/todo-list/lib/todo-list-view.coffee:1:1)
    at Module._compile (module.js:428:26)
    at Object.defineProperty.value [as .coffee] (/Users/Arthur/Desktop/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:169:21)
    at Module.load (module.js:353:32)
    at Function.Module._load (module.js:308:12)
    at Module.require (module.js:363:17)
    at require (module.js:382:17)
```

# Dev
No dev packages
```

**Comment by banmawangqin** [comment]
Mac OS X 10.11.2, same problem.

**Comment by randohinn** [comment]
Same.

Atom Version: 1.4.0
System: Microsoft Windows 10 Pro
Thrown From: todo-list package, v1.0.0

**Comment by placrosse** [comment]
same problem here

**Comment by petonic** [comment]
Same problem on the latest Mac OSX on a brand new install.

**Comment by ttaylordev** [comment]
Atom Version: 1.5.4
System: Windows 10
Package version 1.0.0


TypeError: Cannot read property 'prototype' of undefined
    at __extends (file:///C:/Users/Owner/.atom/packages/todo-list/lib/todo-list-view.coffee:1:1)
    at file:///C:/Users/Owner/.atom/packages/todo-list/lib/todo-list-view.coffee:5:3
    at Object.<anonymous> (file:///C:/Users/Owner/.atom/packages/todo-list/lib/todo-list-view.coffee:5:3)
    at Object.<anonymous> (file:///C:/Users/Owner/.atom/packages/todo-list/lib/todo-list-view.coffee:1:1)
    at Module._compile (C:\Users\Owner\AppData\Local\atom\app-1.5.4\resources\app.asar\src\native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (C:\Users\Owner\AppData\Local\atom\app-1.5.4\resources\app.asar\src\compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (C:\Users\Owner\AppData\Local\atom\app-1.5.4\resources\app.asar\src\native-compile-cache.js:50:27)
    at Object.<anonymous> (file:///C:/Users/Owner/.atom/packages/todo-list/lib/todo-list.coffee:1:16)
    at Object.<anonymous> (file:///C:/Users/Owner/.atom/packages/todo-list/lib/todo-list.coffee:1:1)
    at Module._compile (C:\Users\Owner\AppData\Local\atom\app-1.5.4\resources\app.asar\src\native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (C:\Users\Owner\AppData\Local\atom\app-1.5.4\resources\app.asar\src\compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (C:\Users\Owner\AppData\Local\atom\app-1.5.4\resources\app.asar\src\native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (C:\Users\Owner\AppData\Local\atom\app-1.5.4\resources\app.asar\src\package.js:720:27)
    at C:\Users\Owner\AppData\Local\atom\app-1.5.4\resources\app.asar\src\package.js:116:28
    at Package.module.exports.Package.measure (C:\Users\Owner\AppData\Local\atom\app-1.5.4\resources\app.asar\src\package.js:92:15)
    at Package.module.exports.Package.load (C:\Users\Owner\AppData\Local\atom\app-1.5.4\resources\app.asar\src\package.js:106:12)
    at PackageManager.module.exports.PackageManager.loadPackage (C:\Users\Owner\AppData\Local\atom\app-1.5.4\resources\app.asar\src\package-manager.js:445:14)
    at PackageManager.module.exports.PackageManager.loadPackages (C:\Users\Owner\AppData\Local\atom\app-1.5.4\resources\app.asar\src\package-manager.js:395:14)
    at AtomEnvironment.module.exports.AtomEnvironment.startEditorWindow (C:\Users\Owner\AppData\Local\atom\app-1.5.4\resources\app.asar\src\atom-environment.js:684:21)
    at module.exports (C:\Users\Owner\AppData\Local\atom\app-1.5.4\resources\app.asar\src\initialize-application-window.js:28:10)
    at setupWindow (file:///C:/Users/Owner/AppData/Local/atom/app-1.5.4/resources/app.asar/static/index.js:86:5)
    at window.onload (file:///C:/Users/Owner/AppData/Local/atom/app-1.5.4/resources/app.asar/static/index.js:41:9)

**Comment by comfysquirrel** [comment]
Same problem for me, OS X 10.10, Atom 1.7.3

**Comment by ghost** [comment]
Atom version: 1.8.0
on Windos 7
TypeError: Cannot read property 'prototype' of undefined
    at __extends (file:///C:/Users/Designer/.atom/packages/todo-list/lib/todo-list-view.coffee:1:1)
    at file:///C:/Users/Designer/.atom/packages/todo-list/lib/todo-list-view.coffee:5:3
    at Object.<anonymous> (file:///C:/Users/Designer/.atom/packages/todo-list/lib/todo-list-view.coffee:5:3)
    at Object.<anonymous> (file:///C:/Users/Designer/.atom/packages/todo-list/lib/todo-list-view.coffee:1:1)
    at Module._compile (C:\Users\Designer\AppData\Local\atom\app-1.8.0\resources\app.asar\src\native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee](C:UsersDesignerAppDataLocalatomapp-1.8.0resourcesapp.asarsrccompile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (C:\Users\Designer\AppData\Local\atom\app-1.8.0\resources\app.asar\src\native-compile-cache.js:50:27)
    at Object.<anonymous> (file:///C:/Users/Designer/.atom/packages/todo-list/lib/todo-list.coffee:1:16)
    at Object.<anonymous> (file:///C:/Users/Designer/.atom/packages/todo-list/lib/todo-list.coffee:1:1)
    at Module._compile (C:\Users\Designer\AppData\Local\atom\app-1.8.0\resources\app.asar\src\native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee](C:UsersDesignerAppDataLocalatomapp-1.8.0resourcesapp.asarsrccompile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (C:\Users\Designer\AppData\Local\atom\app-1.8.0\resources\app.asar\src\native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (C:\Users\Designer\AppData\Local\atom\app-1.8.0\resources\app.asar\src\package.js:715:27)
    at C:\Users\Designer\AppData\Local\atom\app-1.8.0\resources\app.asar\src\package.js:117:28
    at Package.module.exports.Package.measure (C:\Users\Designer\AppData\Local\atom\app-1.8.0\resources\app.asar\src\package.js:92:15)
    at Package.module.exports.Package.load (C:\Users\Designer\AppData\Local\atom\app-1.8.0\resources\app.asar\src\package.js:106:12)
    at PackageManager.module.exports.PackageManager.loadPackage (C:\Users\Designer\AppData\Local\atom\app-1.8.0\resources\app.asar\src\package-manager.js:457:14)
    at C:\Users\Designer\AppData\Local\atom\app-1.8.0\resources\app.asar\src\package-manager.js:402:19
    at Config.module.exports.Config.transact (C:\Users\Designer\AppData\Local\atom\app-1.8.0\resources\app.asar\src\config.js:312:16)
    at PackageManager.module.exports.PackageManager.loadPackages (C:\Users\Designer\AppData\Local\atom\app-1.8.0\resources\app.asar\src\package-manager.js:397:19)
    at C:\Users\Designer\AppData\Local\atom\app-1.8.0\resources\app.asar\src\atom-environment.js:743:28

**Comment by jon-freed** [comment]
I came here after getting the same error but then reviewed the repository's front page.

**Please note the message in this repository's readme.md:**

# **"This package is no longer maintained."**

_(I have flagged [the package on atom.io](https://atom.io/packages/todo-list) and recommended that it be removed from there.)_

Note: there are **[other Atom packages for TODO tracking](https://atom.io/packages/search?q=TODO)**.
